[package]
name = "AutoDownloader"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.38"
dict = "0.1.5"
gcookie = "0.1.2"
reqwest = "0.12.9"
tokio = { version = "1.41.1", features = ["full"] }
